// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public final class CompteOuterClass {
  private CompteOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_Compte_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_Compte_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_CompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_CompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_SoldeStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_SoldeStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_GetAllComptesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_GetAllComptesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_GetAllComptesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_GetAllComptesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_GetCompteByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_GetCompteByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_GetCompteByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_GetCompteByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_GetTotalSoldeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_GetTotalSoldeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_GetTotalSoldeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_GetTotalSoldeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_SaveCompteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_SaveCompteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_grpcdemo_SaveCompteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_grpcdemo_SaveCompteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014compte.proto\022\024com.example.grpcdemo\"i\n\006" +
      "Compte\022\n\n\002id\030\001 \001(\t\022\r\n\005solde\030\002 \001(\002\022\024\n\014dat" +
      "eCreation\030\003 \001(\t\022.\n\004type\030\004 \001(\0162 .com.exam" +
      "ple.grpcdemo.TypeCompte\"d\n\rCompteRequest" +
      "\022\r\n\005solde\030\001 \001(\002\022\024\n\014dateCreation\030\002 \001(\t\022.\n" +
      "\004type\030\003 \001(\0162 .com.example.grpcdemo.TypeC" +
      "ompte\"9\n\nSoldeStats\022\r\n\005count\030\001 \001(\005\022\013\n\003su" +
      "m\030\002 \001(\002\022\017\n\007average\030\003 \001(\002\"\026\n\024GetAllCompte" +
      "sRequest\"F\n\025GetAllComptesResponse\022-\n\007com" +
      "ptes\030\001 \003(\0132\034.com.example.grpcdemo.Compte" +
      "\"\"\n\024GetCompteByIdRequest\022\n\n\002id\030\001 \001(\t\"E\n\025" +
      "GetCompteByIdResponse\022,\n\006compte\030\001 \001(\0132\034." +
      "com.example.grpcdemo.Compte\"\026\n\024GetTotalS" +
      "oldeRequest\"H\n\025GetTotalSoldeResponse\022/\n\005" +
      "stats\030\001 \001(\0132 .com.example.grpcdemo.Solde" +
      "Stats\"H\n\021SaveCompteRequest\0223\n\006compte\030\001 \001" +
      "(\0132#.com.example.grpcdemo.CompteRequest\"" +
      "B\n\022SaveCompteResponse\022,\n\006compte\030\001 \001(\0132\034." +
      "com.example.grpcdemo.Compte*&\n\nTypeCompt" +
      "e\022\013\n\007COURANT\020\000\022\013\n\007EPARGNE\020\0012\245\003\n\rCompteSe" +
      "rvice\022e\n\nAllComptes\022*.com.example.grpcde" +
      "mo.GetAllComptesRequest\032+.com.example.gr" +
      "pcdemo.GetAllComptesResponse\022e\n\nCompteBy" +
      "Id\022*.com.example.grpcdemo.GetCompteByIdR" +
      "equest\032+.com.example.grpcdemo.GetCompteB" +
      "yIdResponse\022e\n\nTotalSolde\022*.com.example." +
      "grpcdemo.GetTotalSoldeRequest\032+.com.exam" +
      "ple.grpcdemo.GetTotalSoldeResponse\022_\n\nSa" +
      "veCompte\022\'.com.example.grpcdemo.SaveComp" +
      "teRequest\032(.com.example.grpcdemo.SaveCom" +
      "pteResponseB\030\n\024ma.projet.grpc.stubsP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_grpcdemo_Compte_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_grpcdemo_Compte_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_Compte_descriptor,
        new java.lang.String[] { "Id", "Solde", "DateCreation", "Type", });
    internal_static_com_example_grpcdemo_CompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_grpcdemo_CompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_CompteRequest_descriptor,
        new java.lang.String[] { "Solde", "DateCreation", "Type", });
    internal_static_com_example_grpcdemo_SoldeStats_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_grpcdemo_SoldeStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_SoldeStats_descriptor,
        new java.lang.String[] { "Count", "Sum", "Average", });
    internal_static_com_example_grpcdemo_GetAllComptesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_example_grpcdemo_GetAllComptesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_GetAllComptesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_example_grpcdemo_GetAllComptesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_example_grpcdemo_GetAllComptesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_GetAllComptesResponse_descriptor,
        new java.lang.String[] { "Comptes", });
    internal_static_com_example_grpcdemo_GetCompteByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_example_grpcdemo_GetCompteByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_GetCompteByIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_example_grpcdemo_GetCompteByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_example_grpcdemo_GetCompteByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_GetCompteByIdResponse_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_com_example_grpcdemo_GetTotalSoldeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_example_grpcdemo_GetTotalSoldeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_GetTotalSoldeRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_example_grpcdemo_GetTotalSoldeResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_example_grpcdemo_GetTotalSoldeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_GetTotalSoldeResponse_descriptor,
        new java.lang.String[] { "Stats", });
    internal_static_com_example_grpcdemo_SaveCompteRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_example_grpcdemo_SaveCompteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_SaveCompteRequest_descriptor,
        new java.lang.String[] { "Compte", });
    internal_static_com_example_grpcdemo_SaveCompteResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_example_grpcdemo_SaveCompteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_grpcdemo_SaveCompteResponse_descriptor,
        new java.lang.String[] { "Compte", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
