// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface GetTotalSoldeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTotalSoldeRequest)
    com.google.protobuf.MessageOrBuilder {
}
