// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface SaveCompteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveCompteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CompteRequest compte = 1;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.CompteRequest compte = 1;</code>
   * @return The compte.
   */
  ma.projet.grpc.stubs.CompteRequest getCompte();
  /**
   * <code>.CompteRequest compte = 1;</code>
   */
  ma.projet.grpc.stubs.CompteRequestOrBuilder getCompteOrBuilder();
}
